[style]
Name = Far2l Dark

[farcolors]
# Panel
Panel.Box = foreground:#34e2e2 | background:#3465a4
Panel.Cursor = foreground:#2e3436 | background:#06989a
Panel.Cursor.Selected = foreground:#fce94f | background:#06989a
Panel.Cursor.Inactive = foreground:#d3d7cf | background:#555753
Panel.Cursor.Inactive.Selected = foreground:#fce94f | background:#555753
Panel.Dir = foreground:#eeeeec | background:#3465a4
Panel.FastFindNoMatch = foreground:#ef2929 | background:#3465a4
Panel.Scrollbar = foreground:#34e2e2 | background:#3465a4
Panel.Scrollbar.Minimal = foreground:#eeeeec | background:#3465a4
Panel.Text = foreground:#34e2e2 | background:#3465a4
Panel.Text.Highlight = foreground:#d3d7cf | background:#3465a4
Panel.Text.Info = foreground:#fce94f | background:#3465a4
Panel.Text.Selected = foreground:#fce94f | background:#3465a4
Panel.Title = foreground:#34e2e2 | background:#3465a4
Panel.Title.Column = foreground:#fce94f | background:#3465a4
Panel.Title.Selected = foreground:#2e3436 | background:#06989a
Panel.Info.Total = foreground:#d3d7cf | background:#2e3436
Panel.Info.Selected = foreground:#fce94f | background:#06989a
Table.Box = foreground:#34e2e2 | background:#3465a4
Scrollbar = foreground:#34e2e2 | background:#3465a4

# Dialog
Dialog.Box = foreground:#2e3436 | background:#d3d7cf
Dialog.Box.Title = foreground:#2e3436 | background:#d3d7cf
Dialog.Box.Title.Highlight = foreground:#fce94f | background:#d3d7cf
Dialog.Text = foreground:#2e3436 | background:#d3d7cf
Dialog.Text.Highlight = foreground:#fce94f | background:#d3d7cf
Dialog.Edit = foreground:#eeeeec | background:#555753
Dialog.Button = foreground:#2e3436 | background:#d3d7cf
Dialog.Button.Selected = foreground:#2e3436 | background:#4e9a06
Dialog.Button.Highlight = foreground:#fce94f | background:#d3d7cf
Dialog.Button.Highlight.Selected = foreground:#eeeeec | background:#4e9a06
Dialog.Edit.Unchanged = foreground:#fce94f | background:#4e9a06
Dialog.Edit.Selected = foreground:#fce94f | background:#4e9a06

# Warning message
WarnDialog.Box = foreground:#eeeeec | background:#cc0000
WarnDialog.Box.Title = foreground:#eeeeec | background:#cc0000
WarnDialog.Box.Title.Highlight = foreground:#fce94f | background:#cc0000
WarnDialog.Text = foreground:#eeeeec | background:#cc0000
WarnDialog.Text.Highlight = foreground:#fce94f | background:#cc0000
WarnDialog.Edit = foreground:#2e3436 | background:#06989a
WarnDialog.Button = foreground:#eeeeec | background:#cc0000
WarnDialog.Button.Selected = foreground:#2e3436 | background:#d3d7cf
WarnDialog.Button.Highlight = foreground:#fce94f | background:#cc0000
WarnDialog.Button.Highlight.Selected = foreground:#fce94f | background:#d3d7cf
WarnDialog.Edit.Unchanged = foreground:#2e3436 | background:#06989a
WarnDialog.Edit.Selected = foreground:#2e3436 | background:#d3d7cf

# Menu
Menu.Box = foreground:#2e3436 | background:#555753
Menu.Title = foreground:#2e3436 | background:#d3d7cf
Menu.Text = foreground:#2e3436 | background:#d3d7cf
Menu.Text.Selected = foreground:#2e3436 | background:#4e9a06
Menu.Highlight = foreground:#fce94f | background:#d3d7cf
Menu.Highlight.Selected = foreground:#fce94f | background:#4e9a06

# Horizontal menu
HMenu.Text = foreground:#2e3436 | background:#06989a
HMenu.Text.Selected = foreground:#eeeeec | background:#2e3436
HMenu.Highlight = foreground:#fce94f | background:#06989a
HMenu.Highlight.Selected = foreground:#fce94f | background:#2e3436

# Key bar
Keybar.Num = foreground:#d3d7cf | background:#2e3436
Keybar.Text = foreground:#2e3436 | background:#06989a

# Command line
CommandLine = foreground:#d3d7cf | background:#2e3436
CommandLine.Prefix = foreground:#d3d7cf | background:#2e3436
CommandLine.Selected = foreground:#2e3436 | background:#d3d7cf
CommandLine.Prompt.Inactive = foreground:#555753 | background:#2e3436
CommandLine.UserScreen = foreground:#d3d7cf | background:#2e3436

# Viewer
Viewer.Text = foreground:#eeeeec | background:#555753
Viewer.Status = foreground:#2e3436 | background:#06989a
Viewer.Arrows = foreground:#fce94f | background:#3465a4
Viewer.Scrollbar = foreground:#34e2e2 | background:#3465a4

# Editor
Editor.Text = foreground:#34e2e2 | background:#3465a4
Editor.Scrollbar = foreground:#34e2e2 | background:#3465a4
Editor.Status = foreground:#2e3436 | background:#06989a

# Help
Help.Text = foreground:#2e3436 | background:#06989a
Help.Text.Highlight = foreground:#eeeeec | background:#06989a
Help.Topic = foreground:#fce94f | background:#06989a
Help.Topic.Selected = foreground:#eeeeec | background:#555753
Help.Box = foreground:#2e3436 | background:#06989a
Help.Box.Title = foreground:#2e3436 | background:#06989a